name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create .env file
      run: |
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
        echo "VITE_ANTHROPIC_API_KEY=${{ secrets.VITE_ANTHROPIC_API_KEY }}" >> .env
        echo "VITE_ANTHROPIC_API_URL=https://api.anthropic.com/v1/messages" >> .env
        echo "VITE_APP_NAME=Contigo Wellspring" >> .env
        echo "VITE_APP_VERSION=1.0.0" >> .env
        echo "VITE_APP_DESCRIPTION=Tu compañero de bienestar integral" >> .env
    
    - name: Build web app
      run: npm run build
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Build debug APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon
    
    - name: Build release APK (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon
      env:
        ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    
    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: carolina-wellspring-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
    
    - name: Upload release APK (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: carolina-wellspring-release
        path: android/app/build/outputs/apk/release/app-release.apk
    
    - name: Create Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Carolina Wellspring ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: android/app/build/outputs/apk/release/app-release.apk
        asset_name: carolina-wellspring.apk
        asset_content_type: application/vnd.android.package-archive
